# Generated by Django 4.1.2 on 2022-10-13 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chore_notification_follow_chore_tracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'friend')},
        ),
    ]
