# Generated by Django 4.1.2 on 2022-10-18 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_chore_tracker_complete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore_tracker',
            name='completed_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 18, 14, 1, 39, 779725)),
        ),
    ]
