# Generated by Django 4.1.2 on 2022-10-20 20:52

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_chore_tracker_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore_tracker',
            name='due_date',
            field=models.DateTimeField(default=core.models.Chore_Tracker.get_due_date),
        ),
    ]
