# Generated by Django 4.1.2 on 2022-10-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_chore_tracker_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='chore_tracker',
            name='completed_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
