# Generated by Django 4.1.2 on 2022-10-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_chore_tracker_completed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='chore_tracker',
            name='completed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
