# Generated by Django 4.1.2 on 2022-10-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_chore_tracker_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore_tracker',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
