# Generated by Django 4.1.2 on 2022-10-25 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_chore_tracker_completed_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chore_tracker',
            unique_together={('user', 'chore', 'due_date')},
        ),
    ]
