# Generated by Django 4.1.2 on 2022-10-25 16:16

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_chore_tracker_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chore_tracker',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='chore_tracker',
            name='completed_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chore_tracker',
            name='due_date',
            field=models.DateField(default=core.models.Chore_Tracker.get_due_date),
        ),
        migrations.AddConstraint(
            model_name='chore_tracker',
            constraint=models.UniqueConstraint(fields=('user', 'chore', 'due_date'), name='unique_constraint'),
        ),
    ]
